### PR TITLE
Added `ShopifyLocalization`

### PR DESCRIPTION
**Pull request by asadamatic**
### Purpose

This will allow to fetch [Loaclization](https://shopify.dev/docs/api/storefront/2024-01/queries/localization) object, which will be beneficial to present `Language` and `Currency` options to the user.

### CODE REVIEW

**Comment by asadamatic** [comment]
@imsujan276 Sure, I'll add those in the next commit.

**Comment by asadamatic** [comment]
@imsujan276 I'm added the documentation and example. The example is in the shop tab.

**Comment by imsujan276** [comment]
Hi, thank you for your time for updating the doc. 

But, in the example, I am unable to understand how the fetched data can be used in the app. 
like
1. is it used to fetch localized data from the shopify? If yes, how can one use it ?
2. is it used to just display the supported countries?

**Comment by asadamatic** [comment]
It is used to fetch;
1. Supported languages, which can be used to display language options to the user.
2. Supported countries and their supported currencies, which can be used to display currency options to the user.

Without this data, the developer would need to hardcode the supported languages and currencies.

**Pull request merged**
